apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: physionet-preprocess-challenge2020
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          TTLAfterFinished: 60
          containers:
            - args:
                - apt-get -y update; apt-get -y install git rsync; pip install -r /home/opt/projects/physionet2020/requirements.txt; chown -R 22382:20000 /data/opt/physionet2020/; python -u /home/opt/projects/physionet2020/scripts/preprocess_challenge2020.py --physionet_archive_path /data/opt/physionet2020/original/ --processed_data_path /data/opt/physionet2020/data/raw/complete/; chown -R 22382:20000 /data/opt/physionet2020; chown -R 22382:20000 /output/
              command:
                - sh
                - -c
              image: pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources:
                limits:
                  cpu: 8
                  memory: 16384Mi
                  nvidia.com/gpu: 0
              volumeMounts:
                - mountPath: /data/opt
                  name: nfs-data
                - mountPath: /output
                  name: nfs-output
                - mountPath: /home/opt
                  name: nfs-home
          nodeSelector:
            accelerator: nvidia-tesla-p100
          restartPolicy: OnFailure
          ttlSecondsAfterFinishing: 1
          volumes:
            - name: nfs-data
              persistentVolumeClaim:
                claimName: kflow-opt-data-pvc
            - name: nfs-output
              persistentVolumeClaim:
                claimName: kflow-opt-output-pvc
            - name: nfs-home
              persistentVolumeClaim:
                claimName: kflow-opt-home-pvc
